import { useEffect, useRef, useState } from "react";
import { FiArrowLeft, FiImage, FiSave } from "react-icons/fi";
import toast from "react-hot-toast";
import { useNavigate, useParams } from "react-router-dom";
import DashboardLayout from "../../layouts/DashboardLayout";
import { getVehicle, updateVehicle as persistVehicle } from "../../api/authApi";

const categories = ["Public Works", "Secretary Works", "Ministerial Assignments", "Administrative Transport", "Protocol & VIP Movement", "General Fleet Pool"];
const blank = { registration_number: "", vehicle_type: "", make: "", model: "", manufacturing_year: "", color: "", vin: "", engine_number: "", fuel_type: "", fuel_capacity: "", technical_notes: "", registration_expiry: "", revenue_license_expiry: "", insurance_policy: "", insurance_provider: "", assignment: "", status: "unavailable", last_service_date: "", fuel_level: 0, service_category: "" };

export default function VehicleDatabaseDetails() {
  const { registration } = useParams(); const navigate = useNavigate(); const imageRef = useRef(null);
  const [vehicle, setVehicle] = useState(null); const [image, setImage] = useState(null); const [preview, setPreview] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { const load = async () => { try { const response = await getVehicle(registration); setVehicle({ ...blank, ...response?.data?.vehicle }); } catch (error) { toast.error(error?.message || "Vehicle not found."); setVehicle(false); } }; load(); }, [registration]);
  const change = (event) => setVehicle((current) => ({ ...current, [event.target.name]: event.target.value }));
  const chooseImage = (event) => { const file = event.target.files?.[0]; if (file) { setImage(file); setPreview(URL.createObjectURL(file)); } };
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const data = new FormData(); Object.entries(vehicle).forEach(([key, value]) => { if (!["id", "created_at", "updated_at", "image_path", "image_url"].includes(key) && value !== null) data.append(key, value); }); if (image) data.append("image", image); const response = await persistVehicle(registration, data); setVehicle({ ...blank, ...response.data.vehicle }); setImage(null); setPreview(null); toast.success(response?.message || "Vehicle updated."); } catch (error) { const errors = error?.errors; toast.error(errors ? Object.values(errors).flat()[0] : error?.message || "Unable to update vehicle."); } finally { setSaving(false); } };
  const field = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50";
  if (vehicle === null) return <DashboardLayout><div className="p-6 text-gray-500">Loading vehicle…</div></DashboardLayout>;
  if (vehicle === false) return <DashboardLayout><div className="p-6"><button onClick={() => navigate("/vehicledirectory")} className="rounded-lg bg-blue-600 px-4 py-2 text-white">Back to directory</button></div></DashboardLayout>;
  const imageUrl = preview || vehicle.image_url;
  return <DashboardLayout><form onSubmit={save} className="min-h-screen space-y-6 bg-slate-50 p-6"><header className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><button type="button" onClick={() => navigate("/vehicledirectory")} className="flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600"><FiArrowLeft />Vehicle Directory</button><h1 className="mt-2 text-2xl font-bold text-slate-900">Update Vehicle Details</h1><p className="mt-1 text-sm text-slate-500">All changes are saved to the fleet database.</p></div><button disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><FiSave />{saving ? "Saving..." : "Save changes"}</button></header>
    <div className="grid gap-6 xl:grid-cols-3"><aside className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Vehicle image</h2>{imageUrl ? <img src={imageUrl} alt={vehicle.model} className="mt-4 h-56 w-full rounded-xl object-cover" /> : <div className="mt-4 flex h-56 items-center justify-center rounded-xl bg-slate-100 text-slate-400"><FiImage size={34} /></div>}<button type="button" onClick={() => imageRef.current?.click()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-blue-300 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700"><FiImage />Change vehicle image</button><input ref={imageRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseImage} className="hidden" /></aside>
      <section className="rounded-2xl border bg-white p-5 shadow-sm xl:col-span-2"><h2 className="text-lg font-bold">Operational details</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label>Registration number<input name="registration_number" value={vehicle.registration_number} onChange={change} required className={field} /></label><label>Vehicle type<input name="vehicle_type" value={vehicle.vehicle_type} onChange={change} required className={field} /></label><label>Make<input name="make" value={vehicle.make} onChange={change} required className={field} /></label><label>Model<input name="model" value={vehicle.model} onChange={change} required className={field} /></label><label>Vehicle status<select name="status" value={vehicle.status} onChange={change} className={field}><option value="available">Available</option><option value="unavailable">Unavailable</option><option value="maintenance">Maintenance</option></select></label><label>Last service date<input type="date" name="last_service_date" value={vehicle.last_service_date || ""} onChange={change} className={field} /></label><label>Service category<select name="service_category" value={vehicle.service_category || ""} onChange={change} className={field}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Assignment<input name="assignment" value={vehicle.assignment || ""} onChange={change} className={field} /></label><div className="md:col-span-2"><label>Fuel level: <span className="font-semibold text-blue-600">{vehicle.fuel_level}%</span><input type="range" name="fuel_level" min="0" max="100" value={vehicle.fuel_level} onChange={change} className="mt-3 w-full accent-blue-600" /></label></div></div></section></div>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Technical and compliance details</h2><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><label>Manufacturing year<input type="number" name="manufacturing_year" value={vehicle.manufacturing_year || ""} onChange={change} className={field} /></label><label>Colour<input name="color" value={vehicle.color || ""} onChange={change} className={field} /></label><label>VIN<input name="vin" value={vehicle.vin || ""} onChange={change} className={field} /></label><label>Engine number<input name="engine_number" value={vehicle.engine_number || ""} onChange={change} className={field} /></label><label>Fuel type<input name="fuel_type" value={vehicle.fuel_type || ""} onChange={change} className={field} /></label><label>Fuel capacity<input type="number" name="fuel_capacity" value={vehicle.fuel_capacity || ""} onChange={change} className={field} /></label><label>Registration expiry<input type="date" name="registration_expiry" value={vehicle.registration_expiry || ""} onChange={change} className={field} /></label><label>Revenue licence expiry<input type="date" name="revenue_license_expiry" value={vehicle.revenue_license_expiry || ""} onChange={change} className={field} /></label><label>Insurance policy<input name="insurance_policy" value={vehicle.insurance_policy || ""} onChange={change} className={field} /></label><label>Insurance provider<input name="insurance_provider" value={vehicle.insurance_provider || ""} onChange={change} className={field} /></label><label className="md:col-span-2 xl:col-span-3">Technical notes<textarea name="technical_notes" rows="4" value={vehicle.technical_notes || ""} onChange={change} className={field} /></label></div></section></form></DashboardLayout>;
}
