import { FiDatabase, FiDownload, FiShield } from "react-icons/fi";

export default function DatabaseManagementSection({ creatingBackup, onCreateBackup }) {
  return (
    <section aria-labelledby="database-management-title">
      <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.25em] text-blue-700">System protection</p>
          <h1 id="database-management-title" className="mt-1 text-3xl font-bold text-slate-900">Database Management</h1>
          <p className="mt-2 text-sm text-slate-500">Create a secure, complete backup of the vehicle management database.</p>
        </div>
        <span className="rounded-xl bg-blue-50 p-3 text-blue-700"><FiDatabase className="h-6 w-6" aria-hidden="true" /></span>
      </header>

      <div className="mt-8 grid gap-5 md:grid-cols-3">
        <Detail label="Backup scope" value="Complete database" />
        <Detail label="Delivery" value="Secure download" />
        <Detail label="Recommended use" value="Before major changes" />
      </div>
      <div className="mt-8 rounded-2xl border border-blue-200 bg-blue-50/50 p-6">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-start gap-3"><FiShield className="mt-1 text-blue-700" aria-hidden="true" /><div><h2 className="font-bold text-slate-900">Create database backup</h2><p className="mt-1 text-sm text-slate-600">The backup is generated by the server and downloaded to this device.</p></div></div>
          <button type="button" onClick={onCreateBackup} disabled={creatingBackup} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-blue-700 px-5 py-3 text-sm font-semibold text-white transition hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-60"><FiDownload aria-hidden="true" /> {creatingBackup ? "Creating backup..." : "Create backup"}</button>
        </div>
      </div>
    </section>
  );
}

function Detail({ label, value }) {
  return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 font-semibold text-slate-900">{value}</p></div>;
}
