import { FiCheckCircle, FiClock, FiDatabase, FiDownload, FiFileText, FiShield } from "react-icons/fi";

export default function DatabaseManagementSection({ backups, loadingBackups, backupHistoryError, creatingBackup, onCreateBackup }) {
  const latestBackup = backups[0];

  return (
    <section aria-labelledby="database-management-title" className="space-y-6">
      <header>
        <p className="text-xs font-bold uppercase tracking-[0.24em] text-blue-700">System protection</p>
        <h1 id="database-management-title" className="mt-1 text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl">Database Management</h1>
        <p className="mt-2 text-sm text-slate-500">Create a secure, complete backup of the vehicle management database.</p>
      </header>

      <div className="grid gap-4 md:grid-cols-3">
        <StatusCard
          icon={FiDatabase}
          iconClassName="bg-emerald-50 text-emerald-600"
          label="Last backup"
          value={latestBackup ? formatDate(latestBackup.created_at) : "No backups created yet"}
          detail={latestBackup ? "Completed successfully" : "Create one whenever a protected copy is needed."}
          completed={Boolean(latestBackup)}
        />
        <StatusCard icon={FiClock} iconClassName="bg-blue-50 text-blue-600" label="Backup frequency" value="Manual (on demand)" detail="Run a backup whenever you need it." />
        <StatusCard icon={FiShield} iconClassName="bg-violet-50 text-violet-600" label="Storage status" value="Private delivery" detail="The server copy is removed after download." />
      </div>

      <div className="rounded-2xl border border-blue-100 bg-linear-to-r from-blue-50/90 via-slate-50 to-indigo-50/80 p-4 sm:p-5">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex min-w-0 items-start gap-3">
            <span className="rounded-xl bg-blue-100 p-3 text-blue-700"><FiDatabase className="h-5 w-5" aria-hidden="true" /></span>
            <div>
              <h2 className="font-bold text-slate-900">Create database backup</h2>
              <p className="mt-1 text-sm text-slate-600">The backup is generated by the server and downloaded to this device.</p>
            </div>
          </div>
          <button type="button" onClick={onCreateBackup} disabled={creatingBackup} className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-lg bg-blue-700 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-200 disabled:cursor-not-allowed disabled:opacity-60"><FiDownload aria-hidden="true" /> {creatingBackup ? "Creating backup..." : "Create backup"}</button>
        </div>
      </div>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white" aria-labelledby="backup-history-title">
        <header className="flex items-center gap-3 border-b border-slate-100 px-4 py-4 sm:px-5">
          <span className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><FiClock className="h-5 w-5" aria-hidden="true" /></span>
          <div>
            <h2 id="backup-history-title" className="font-bold text-slate-900">Backup History</h2>
            <p className="text-xs text-slate-500">Completed backup records are retained after refresh.</p>
          </div>
        </header>

        {loadingBackups ? (
          <div className="flex items-center justify-center px-5 py-10 text-sm text-slate-500">
            Loading backup history...
          </div>
        ) : backupHistoryError ? (
          <div className="px-5 py-10 text-center text-sm text-red-600">
            {backupHistoryError}
          </div>
        ) : backups.length === 0 ? (
          <div className="flex flex-col items-center justify-center px-5 py-10 text-center">
            <span className="rounded-full bg-slate-50 p-3 text-slate-400"><FiFileText className="h-5 w-5" aria-hidden="true" /></span>
            <p className="mt-3 text-sm text-slate-500">No completed backups have been recorded yet.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-[760px] w-full text-left text-sm">
              <thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wide text-slate-500">
                <tr><th scope="col" className="px-5 py-3">Backup date &amp; time</th><th scope="col" className="px-5 py-3">Created by</th><th scope="col" className="px-5 py-3">File name</th><th scope="col" className="px-5 py-3">File size</th><th scope="col" className="px-5 py-3">Status</th></tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {backups.map((backup) => (
                  <tr key={backup.id} className="hover:bg-slate-50/70">
                    <td className="px-5 py-3.5 font-medium text-slate-700"><time dateTime={dateTimeAttribute(backup.created_at)}>{formatDate(backup.created_at)}</time></td>
                    <td className="px-5 py-3.5 text-slate-600">{backup.creator?.name || "Removed user"}</td>
                    <td className="px-5 py-3.5 font-mono text-xs text-slate-600" data-no-translate>{backup.filename}</td>
                    <td className="px-5 py-3.5 text-slate-600" data-no-translate>{formatFileSize(backup.size_bytes)}</td>
                    <td className="px-5 py-3.5"><span className="inline-flex items-center gap-2 text-emerald-600"><span className="h-2 w-2 rounded-full bg-emerald-500" aria-hidden="true" />Completed</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </section>
  );
}

function StatusCard({ icon: Icon, iconClassName, label, value, detail, completed = false }) {
  return <article className="flex min-w-0 gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
    <span className={`h-fit rounded-xl p-2.5 ${iconClassName}`}><Icon className="h-5 w-5" aria-hidden="true" /></span>
    <div className="min-w-0">
      <p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-1 truncate text-sm font-bold text-slate-900" title={value}>{value}</p>
      <p className={`mt-1.5 flex items-center gap-1.5 text-xs ${completed ? "text-emerald-600" : "text-slate-500"}`}>{completed && <FiCheckCircle aria-hidden="true" />}{detail}</p>
    </div>
  </article>;
}

function formatDate(value) {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) return "Not recorded";
  return new Intl.DateTimeFormat(undefined, { day: "2-digit", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" }).format(date);
}

function dateTimeAttribute(value) {
  const date = value ? new Date(value) : null;
  return date && !Number.isNaN(date.getTime()) ? date.toISOString() : undefined;
}

function formatFileSize(size) {
  if (!Number.isFinite(size) || size < 1024) return `${size || 0} B`;
  if (size < 1024 ** 2) return `${(size / 1024).toFixed(1)} KB`;
  return `${(size / (1024 ** 2)).toFixed(1)} MB`;
}
