import { FiPlus, FiTrash2 } from "react-icons/fi";

export default function DepartmentManagementSection({ addingDepartment, departmentName, departments, onAddDepartment, onRemoveDepartment, removingDepartmentId, setDepartmentName }) {
  return (
    <section className="mt-8 rounded-2xl border border-cyan-200 bg-cyan-50/40 p-5" aria-labelledby="department-management-title">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-700">Organization setup</p><h2 id="department-management-title" className="mt-1 text-2xl font-bold text-slate-900">Department Management</h2><p className="mt-1 text-sm text-slate-500">Create and maintain departments separately from user accounts.</p></div><div className="rounded-xl bg-white px-4 py-3 text-sm font-semibold text-cyan-800 shadow-sm">{departments.length} departments</div></div>
      <form onSubmit={onAddDepartment} className="mt-5 flex flex-col gap-3 sm:flex-row"><label className="flex-1"><span className="sr-only">Department name</span><input value={departmentName} onChange={(event) => setDepartmentName(event.target.value)} maxLength="255" required placeholder="Enter department name" className="w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-cyan-500 focus:ring-2 focus:ring-cyan-100" /></label><button type="submit" disabled={addingDepartment || !departmentName.trim()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-cyan-700 px-5 py-3 text-sm font-semibold text-white transition hover:bg-cyan-800 disabled:cursor-not-allowed disabled:opacity-60"><FiPlus aria-hidden="true" /> {addingDepartment ? "Adding..." : "Add department"}</button></form>
      <div className="mt-4 flex max-h-36 flex-wrap gap-2 overflow-y-auto">{departments.length === 0 ? <p className="text-sm text-slate-500">No departments configured.</p> : departments.map((department) => <span key={department.id} className="inline-flex items-center gap-1 rounded-full border border-cyan-100 bg-white py-1 pl-3 pr-1 text-xs font-semibold text-slate-700 shadow-sm">{department.name}<button type="button" onClick={() => onRemoveDepartment(department)} disabled={removingDepartmentId === department.id} title={`Remove ${department.name}`} aria-label={`Remove ${department.name}`} className="rounded-full p-1.5 text-slate-400 transition hover:bg-red-100 hover:text-red-700 disabled:cursor-not-allowed disabled:opacity-50"><FiTrash2 aria-hidden="true" /></button></span>)}</div>
    </section>
  );
}
