<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    /** Seed the government fleet with representative vehicle records. */
    public function run(): void
    {
        foreach ($this->vehicles() as $vehicle) {
            $vehicle['seat_capacity'] = $this->seatCapacities()[$vehicle['registration_number']];

            Vehicle::updateOrCreate(
                ['registration_number' => $vehicle['registration_number']],
                $vehicle,
            );
        }
    }

    /** @return array<string, int> */
    private function seatCapacities(): array
    {
        return [
            'GV-1001' => 7, 'GV-1002' => 5, 'GV-1003' => 5, 'GV-1004' => 14, 'GV-1005' => 7,
            'GV-1006' => 35, 'GV-1007' => 5, 'GV-1008' => 5, 'GV-1009' => 5, 'GV-1010' => 12,
            'GV-1011' => 5, 'GV-1012' => 5, 'GV-1013' => 5, 'GV-1014' => 28, 'GV-1015' => 8,
            'GV-1016' => 5, 'GV-1017' => 5, 'GV-1018' => 5, 'GV-1019' => 8, 'GV-1020' => 5,
            'GV-1021' => 7, 'GV-1022' => 40, 'GV-1023' => 5, 'GV-1024' => 14, 'GV-1025' => 5,
            'GV-1026' => 5, 'GV-1027' => 5, 'GV-1028' => 30, 'GV-1029' => 12, 'GV-1030' => 7,
        ];
    }

    /** @return array<int, array<string, mixed>> */
    private function vehicles(): array
    {
        return [
            ['registration_number' => 'GV-1001', 'vehicle_type' => 'SUV', 'make' => 'Toyota', 'model' => 'Land Cruiser Prado', 'manufacturing_year' => 2021, 'color' => 'White', 'vin' => 'JTEBR3FJ0M5001001', 'engine_number' => '1GD-1001001', 'fuel_type' => 'Diesel', 'fuel_capacity' => 87, 'technical_notes' => 'Executive transport vehicle.', 'registration_expiry' => '2027-01-31', 'revenue_license_expiry' => '2027-01-31', 'insurance_policy' => 'GIC-MV-1001', 'insurance_provider' => 'Sri Lanka Insurance', 'assignment' => 'Secretary Office', 'status' => 'available', 'last_service_date' => '2026-05-20', 'fuel_level' => 84, 'service_category' => 'Executive Transport'],
            ['registration_number' => 'GV-1002', 'vehicle_type' => 'Sedan', 'make' => 'Toyota', 'model' => 'Camry', 'manufacturing_year' => 2020, 'color' => 'Black', 'vin' => '4T1G11AK0LU100002', 'engine_number' => '2AR-1001002', 'fuel_type' => 'Petrol', 'fuel_capacity' => 60, 'technical_notes' => 'Official pool sedan.', 'registration_expiry' => '2027-02-15', 'revenue_license_expiry' => '2027-02-15', 'insurance_policy' => 'GIC-MV-1002', 'insurance_provider' => 'Ceylinco Insurance', 'assignment' => 'General Fleet Pool', 'status' => 'available', 'last_service_date' => '2026-06-03', 'fuel_level' => 72, 'service_category' => 'Administration'],
            ['registration_number' => 'GV-1003', 'vehicle_type' => 'Pickup', 'make' => 'Toyota', 'model' => 'Hilux', 'manufacturing_year' => 2022, 'color' => 'Silver', 'vin' => 'MR0HA3CD900100003', 'engine_number' => '2GD-1001003', 'fuel_type' => 'Diesel', 'fuel_capacity' => 80, 'technical_notes' => 'Four-wheel-drive field vehicle.', 'registration_expiry' => '2027-03-10', 'revenue_license_expiry' => '2027-03-10', 'insurance_policy' => 'GIC-MV-1003', 'insurance_provider' => 'Allianz Lanka', 'assignment' => 'Public Works Department', 'status' => 'available', 'last_service_date' => '2026-05-28', 'fuel_level' => 91, 'service_category' => 'Public Works'],
            ['registration_number' => 'GV-1004', 'vehicle_type' => 'Van', 'make' => 'Toyota', 'model' => 'Hiace', 'manufacturing_year' => 2019, 'color' => 'White', 'vin' => 'JTFSX22P606100004', 'engine_number' => '1KD-1001004', 'fuel_type' => 'Diesel', 'fuel_capacity' => 70, 'technical_notes' => 'Staff transport van, 14 seats.', 'registration_expiry' => '2026-11-20', 'revenue_license_expiry' => '2026-11-20', 'insurance_policy' => 'GIC-MV-1004', 'insurance_provider' => 'People’s Insurance', 'assignment' => 'Human Resources Division', 'status' => 'unavailable', 'last_service_date' => '2026-06-22', 'fuel_level' => 35, 'service_category' => 'Staff Transport'],
            ['registration_number' => 'GV-1005', 'vehicle_type' => 'SUV', 'make' => 'Mitsubishi', 'model' => 'Montero Sport', 'manufacturing_year' => 2021, 'color' => 'Grey', 'vin' => 'MMAGUKS10MH100005', 'engine_number' => '4N15-1001005', 'fuel_type' => 'Diesel', 'fuel_capacity' => 68, 'technical_notes' => 'Regional inspection vehicle.', 'registration_expiry' => '2027-04-05', 'revenue_license_expiry' => '2027-04-05', 'insurance_policy' => 'GIC-MV-1005', 'insurance_provider' => 'Fairfirst Insurance', 'assignment' => 'Regional Administration', 'status' => 'available', 'last_service_date' => '2026-06-10', 'fuel_level' => 66, 'service_category' => 'Field Operations'],
            ['registration_number' => 'GV-1006', 'vehicle_type' => 'Bus', 'make' => 'Ashok Leyland', 'model' => 'Lynx', 'manufacturing_year' => 2018, 'color' => 'Blue', 'vin' => 'MB1TCR1A0JH100006', 'engine_number' => 'H6E-1001006', 'fuel_type' => 'Diesel', 'fuel_capacity' => 180, 'technical_notes' => 'Thirty-five seat staff bus.', 'registration_expiry' => '2026-10-18', 'revenue_license_expiry' => '2026-10-18', 'insurance_policy' => 'GIC-MV-1006', 'insurance_provider' => 'Sri Lanka Insurance', 'assignment' => 'Staff Transport Unit', 'status' => 'maintenance', 'last_service_date' => '2026-04-30', 'fuel_level' => 18, 'service_category' => 'Staff Transport'],
            ['registration_number' => 'GV-1007', 'vehicle_type' => 'Sedan', 'make' => 'Honda', 'model' => 'Civic', 'manufacturing_year' => 2020, 'color' => 'Pearl White', 'vin' => 'MRHFC1680LT100007', 'engine_number' => 'L15B-1001007', 'fuel_type' => 'Petrol', 'fuel_capacity' => 47, 'technical_notes' => 'Department officer vehicle.', 'registration_expiry' => '2027-01-12', 'revenue_license_expiry' => '2027-01-12', 'insurance_policy' => 'GIC-MV-1007', 'insurance_provider' => 'Ceylinco Insurance', 'assignment' => 'Finance Division', 'status' => 'available', 'last_service_date' => '2026-06-17', 'fuel_level' => 78, 'service_category' => 'Administration'],
            ['registration_number' => 'GV-1008', 'vehicle_type' => 'Pickup', 'make' => 'Isuzu', 'model' => 'D-Max', 'manufacturing_year' => 2022, 'color' => 'White', 'vin' => 'MPATFS87JNT100008', 'engine_number' => '4JJ3-1001008', 'fuel_type' => 'Diesel', 'fuel_capacity' => 76, 'technical_notes' => 'Equipment transport vehicle.', 'registration_expiry' => '2027-05-08', 'revenue_license_expiry' => '2027-05-08', 'insurance_policy' => 'GIC-MV-1008', 'insurance_provider' => 'Allianz Lanka', 'assignment' => 'Engineering Division', 'status' => 'available', 'last_service_date' => '2026-06-01', 'fuel_level' => 88, 'service_category' => 'Public Works'],
            ['registration_number' => 'GV-1009', 'vehicle_type' => 'SUV', 'make' => 'Nissan', 'model' => 'X-Trail', 'manufacturing_year' => 2019, 'color' => 'Black', 'vin' => 'JN1TANT32U0100009', 'engine_number' => 'MR20-1001009', 'fuel_type' => 'Petrol', 'fuel_capacity' => 60, 'technical_notes' => 'Inter-agency travel vehicle.', 'registration_expiry' => '2026-12-09', 'revenue_license_expiry' => '2026-12-09', 'insurance_policy' => 'GIC-MV-1009', 'insurance_provider' => 'People’s Insurance', 'assignment' => 'Planning Division', 'status' => 'unavailable', 'last_service_date' => '2026-06-14', 'fuel_level' => 42, 'service_category' => 'Administration'],
            ['registration_number' => 'GV-1010', 'vehicle_type' => 'Van', 'make' => 'Nissan', 'model' => 'Caravan', 'manufacturing_year' => 2021, 'color' => 'Silver', 'vin' => 'VWE25-10010100001', 'engine_number' => 'YD25-1001010', 'fuel_type' => 'Diesel', 'fuel_capacity' => 65, 'technical_notes' => 'Mobile service support van.', 'registration_expiry' => '2027-02-28', 'revenue_license_expiry' => '2027-02-28', 'insurance_policy' => 'GIC-MV-1010', 'insurance_provider' => 'Fairfirst Insurance', 'assignment' => 'ICT Division', 'status' => 'available', 'last_service_date' => '2026-05-25', 'fuel_level' => 63, 'service_category' => 'Technical Services'],
            ['registration_number' => 'GV-1011', 'vehicle_type' => 'Sedan', 'make' => 'Toyota', 'model' => 'Corolla', 'manufacturing_year' => 2021, 'color' => 'Silver', 'vin' => 'JTDBR32E0M1001011', 'engine_number' => '2ZR-1001011', 'fuel_type' => 'Petrol', 'fuel_capacity' => 50, 'technical_notes' => 'Administrative travel vehicle.', 'registration_expiry' => '2027-03-01', 'revenue_license_expiry' => '2027-03-01', 'insurance_policy' => 'GIC-MV-1011', 'insurance_provider' => 'Sri Lanka Insurance', 'assignment' => 'Procurement Division', 'status' => 'available', 'last_service_date' => '2026-06-19', 'fuel_level' => 70, 'service_category' => 'Administration'],
            ['registration_number' => 'GV-1012', 'vehicle_type' => 'SUV', 'make' => 'Kia', 'model' => 'Sportage', 'manufacturing_year' => 2022, 'color' => 'Dark Blue', 'vin' => 'KNAPN81BMN7101012', 'engine_number' => 'D4HA-1001012', 'fuel_type' => 'Diesel', 'fuel_capacity' => 62, 'technical_notes' => 'Monitoring and evaluation vehicle.', 'registration_expiry' => '2027-06-15', 'revenue_license_expiry' => '2027-06-15', 'insurance_policy' => 'GIC-MV-1012', 'insurance_provider' => 'Ceylinco Insurance', 'assignment' => 'Monitoring Unit', 'status' => 'available', 'last_service_date' => '2026-06-05', 'fuel_level' => 82, 'service_category' => 'Field Operations'],
            ['registration_number' => 'GV-1013', 'vehicle_type' => 'Pickup', 'make' => 'Ford', 'model' => 'Ranger', 'manufacturing_year' => 2020, 'color' => 'Orange', 'vin' => 'MNBLMFE10LW101013', 'engine_number' => 'P5AT-1001013', 'fuel_type' => 'Diesel', 'fuel_capacity' => 80, 'technical_notes' => 'Disaster response support vehicle.', 'registration_expiry' => '2027-01-25', 'revenue_license_expiry' => '2027-01-25', 'insurance_policy' => 'GIC-MV-1013', 'insurance_provider' => 'Allianz Lanka', 'assignment' => 'Disaster Management Unit', 'status' => 'available', 'last_service_date' => '2026-05-29', 'fuel_level' => 95, 'service_category' => 'Emergency Response'],
            ['registration_number' => 'GV-1014', 'vehicle_type' => 'Bus', 'make' => 'Tata', 'model' => 'Starbus', 'manufacturing_year' => 2019, 'color' => 'White', 'vin' => 'MAT448004KH101014', 'engine_number' => 'CR4-1001014', 'fuel_type' => 'Diesel', 'fuel_capacity' => 160, 'technical_notes' => 'Twenty-eight seat field team bus.', 'registration_expiry' => '2026-09-30', 'revenue_license_expiry' => '2026-09-30', 'insurance_policy' => 'GIC-MV-1014', 'insurance_provider' => 'People’s Insurance', 'assignment' => 'Field Operations Unit', 'status' => 'maintenance', 'last_service_date' => '2026-04-18', 'fuel_level' => 22, 'service_category' => 'Staff Transport'],
            ['registration_number' => 'GV-1015', 'vehicle_type' => 'Van', 'make' => 'Toyota', 'model' => 'TownAce', 'manufacturing_year' => 2020, 'color' => 'White', 'vin' => 'S402M-10010150001', 'engine_number' => '3SZ-1001015', 'fuel_type' => 'Petrol', 'fuel_capacity' => 43, 'technical_notes' => 'Document delivery vehicle.', 'registration_expiry' => '2027-04-20', 'revenue_license_expiry' => '2027-04-20', 'insurance_policy' => 'GIC-MV-1015', 'insurance_provider' => 'Fairfirst Insurance', 'assignment' => 'Registry Division', 'status' => 'available', 'last_service_date' => '2026-06-16', 'fuel_level' => 57, 'service_category' => 'Logistics'],
            ['registration_number' => 'GV-1016', 'vehicle_type' => 'Sedan', 'make' => 'Hyundai', 'model' => 'Elantra', 'manufacturing_year' => 2021, 'color' => 'Grey', 'vin' => 'KMHD84LF0MU101016', 'engine_number' => 'G4NH-1001016', 'fuel_type' => 'Petrol', 'fuel_capacity' => 50, 'technical_notes' => 'Protocol office vehicle.', 'registration_expiry' => '2027-05-31', 'revenue_license_expiry' => '2027-05-31', 'insurance_policy' => 'GIC-MV-1016', 'insurance_provider' => 'Sri Lanka Insurance', 'assignment' => 'Protocol Office', 'status' => 'available', 'last_service_date' => '2026-06-08', 'fuel_level' => 75, 'service_category' => 'Executive Transport'],
            ['registration_number' => 'GV-1017', 'vehicle_type' => 'SUV', 'make' => 'Suzuki', 'model' => 'Vitara', 'manufacturing_year' => 2020, 'color' => 'Red', 'vin' => 'TSMLYDA1S00A101017', 'engine_number' => 'K14C-1001017', 'fuel_type' => 'Petrol', 'fuel_capacity' => 47, 'technical_notes' => 'District coordination vehicle.', 'registration_expiry' => '2027-02-06', 'revenue_license_expiry' => '2027-02-06', 'insurance_policy' => 'GIC-MV-1017', 'insurance_provider' => 'Ceylinco Insurance', 'assignment' => 'District Coordination Unit', 'status' => 'unavailable', 'last_service_date' => '2026-06-12', 'fuel_level' => 39, 'service_category' => 'Field Operations'],
            ['registration_number' => 'GV-1018', 'vehicle_type' => 'Pickup', 'make' => 'Mitsubishi', 'model' => 'L200', 'manufacturing_year' => 2021, 'color' => 'White', 'vin' => 'MMBJJKL10MH101018', 'engine_number' => '4N15-1001018', 'fuel_type' => 'Diesel', 'fuel_capacity' => 75, 'technical_notes' => 'Maintenance crew vehicle.', 'registration_expiry' => '2027-03-22', 'revenue_license_expiry' => '2027-03-22', 'insurance_policy' => 'GIC-MV-1018', 'insurance_provider' => 'Allianz Lanka', 'assignment' => 'Facilities Management', 'status' => 'available', 'last_service_date' => '2026-06-02', 'fuel_level' => 86, 'service_category' => 'Public Works'],
            ['registration_number' => 'GV-1019', 'vehicle_type' => 'Van', 'make' => 'Mazda', 'model' => 'Bongo', 'manufacturing_year' => 2018, 'color' => 'Silver', 'vin' => 'SKP2V-10190000001', 'engine_number' => 'RF-1001019', 'fuel_type' => 'Diesel', 'fuel_capacity' => 55, 'technical_notes' => 'Stores and supplies transport.', 'registration_expiry' => '2026-12-18', 'revenue_license_expiry' => '2026-12-18', 'insurance_policy' => 'GIC-MV-1019', 'insurance_provider' => 'People’s Insurance', 'assignment' => 'Central Stores', 'status' => 'available', 'last_service_date' => '2026-05-15', 'fuel_level' => 61, 'service_category' => 'Logistics'],
            ['registration_number' => 'GV-1020', 'vehicle_type' => 'Sedan', 'make' => 'Nissan', 'model' => 'Sylphy', 'manufacturing_year' => 2019, 'color' => 'Black', 'vin' => 'B17-1010200000001', 'engine_number' => 'MRA8-1001020', 'fuel_type' => 'Petrol', 'fuel_capacity' => 52, 'technical_notes' => 'Audit division vehicle.', 'registration_expiry' => '2027-01-18', 'revenue_license_expiry' => '2027-01-18', 'insurance_policy' => 'GIC-MV-1020', 'insurance_provider' => 'Fairfirst Insurance', 'assignment' => 'Internal Audit Division', 'status' => 'available', 'last_service_date' => '2026-06-11', 'fuel_level' => 68, 'service_category' => 'Administration'],
            ['registration_number' => 'GV-1021', 'vehicle_type' => 'SUV', 'make' => 'Toyota', 'model' => 'Fortuner', 'manufacturing_year' => 2023, 'color' => 'White', 'vin' => 'MR0HA3FS700102021', 'engine_number' => '1GD-1001021', 'fuel_type' => 'Diesel', 'fuel_capacity' => 80, 'technical_notes' => 'Senior official transport.', 'registration_expiry' => '2027-07-12', 'revenue_license_expiry' => '2027-07-12', 'insurance_policy' => 'GIC-MV-1021', 'insurance_provider' => 'Sri Lanka Insurance', 'assignment' => 'Deputy Secretary Office', 'status' => 'available', 'last_service_date' => '2026-06-24', 'fuel_level' => 90, 'service_category' => 'Executive Transport'],
            ['registration_number' => 'GV-1022', 'vehicle_type' => 'Bus', 'make' => 'Ashok Leyland', 'model' => 'Viking', 'manufacturing_year' => 2020, 'color' => 'Blue', 'vin' => 'MB1B2D2A0LH102022', 'engine_number' => 'H6E-1001022', 'fuel_type' => 'Diesel', 'fuel_capacity' => 200, 'technical_notes' => 'Forty seat staff bus.', 'registration_expiry' => '2027-02-22', 'revenue_license_expiry' => '2027-02-22', 'insurance_policy' => 'GIC-MV-1022', 'insurance_provider' => 'Ceylinco Insurance', 'assignment' => 'Staff Transport Unit', 'status' => 'available', 'last_service_date' => '2026-05-31', 'fuel_level' => 74, 'service_category' => 'Staff Transport'],
            ['registration_number' => 'GV-1023', 'vehicle_type' => 'Pickup', 'make' => 'Mahindra', 'model' => 'Scorpio Getaway', 'manufacturing_year' => 2019, 'color' => 'Grey', 'vin' => 'MA1TJ2GH0K6102023', 'engine_number' => 'MHAWK-1001023', 'fuel_type' => 'Diesel', 'fuel_capacity' => 60, 'technical_notes' => 'Rural field inspection vehicle.', 'registration_expiry' => '2026-11-15', 'revenue_license_expiry' => '2026-11-15', 'insurance_policy' => 'GIC-MV-1023', 'insurance_provider' => 'Allianz Lanka', 'assignment' => 'Rural Development Unit', 'status' => 'maintenance', 'last_service_date' => '2026-04-25', 'fuel_level' => 15, 'service_category' => 'Field Operations'],
            ['registration_number' => 'GV-1024', 'vehicle_type' => 'Van', 'make' => 'Toyota', 'model' => 'Regius Ace', 'manufacturing_year' => 2022, 'color' => 'White', 'vin' => 'GDH201-1001024001', 'engine_number' => '1GD-1001024', 'fuel_type' => 'Diesel', 'fuel_capacity' => 70, 'technical_notes' => 'Mobile training unit vehicle.', 'registration_expiry' => '2027-05-14', 'revenue_license_expiry' => '2027-05-14', 'insurance_policy' => 'GIC-MV-1024', 'insurance_provider' => 'People’s Insurance', 'assignment' => 'Training Division', 'status' => 'available', 'last_service_date' => '2026-06-09', 'fuel_level' => 79, 'service_category' => 'Technical Services'],
            ['registration_number' => 'GV-1025', 'vehicle_type' => 'Sedan', 'make' => 'Honda', 'model' => 'Accord', 'manufacturing_year' => 2020, 'color' => 'Metallic Grey', 'vin' => 'JHMCR2F30LC102025', 'engine_number' => 'L15B-1001025', 'fuel_type' => 'Petrol', 'fuel_capacity' => 56, 'technical_notes' => 'Legal affairs travel vehicle.', 'registration_expiry' => '2027-04-11', 'revenue_license_expiry' => '2027-04-11', 'insurance_policy' => 'GIC-MV-1025', 'insurance_provider' => 'Fairfirst Insurance', 'assignment' => 'Legal Division', 'status' => 'available', 'last_service_date' => '2026-06-13', 'fuel_level' => 64, 'service_category' => 'Administration'],
            ['registration_number' => 'GV-1026', 'vehicle_type' => 'SUV', 'make' => 'Hyundai', 'model' => 'Tucson', 'manufacturing_year' => 2021, 'color' => 'Silver', 'vin' => 'TMAJ3812GMJ102026', 'engine_number' => 'D4HA-1001026', 'fuel_type' => 'Diesel', 'fuel_capacity' => 62, 'technical_notes' => 'Project supervision vehicle.', 'registration_expiry' => '2027-06-20', 'revenue_license_expiry' => '2027-06-20', 'insurance_policy' => 'GIC-MV-1026', 'insurance_provider' => 'Sri Lanka Insurance', 'assignment' => 'Project Management Unit', 'status' => 'unavailable', 'last_service_date' => '2026-06-20', 'fuel_level' => 28, 'service_category' => 'Field Operations'],
            ['registration_number' => 'GV-1027', 'vehicle_type' => 'Pickup', 'make' => 'Toyota', 'model' => 'Hilux Revo', 'manufacturing_year' => 2023, 'color' => 'White', 'vin' => 'MR0HA3CD800102027', 'engine_number' => '2GD-1001027', 'fuel_type' => 'Diesel', 'fuel_capacity' => 80, 'technical_notes' => 'New infrastructure project vehicle.', 'registration_expiry' => '2027-07-05', 'revenue_license_expiry' => '2027-07-05', 'insurance_policy' => 'GIC-MV-1027', 'insurance_provider' => 'Ceylinco Insurance', 'assignment' => 'Infrastructure Division', 'status' => 'available', 'last_service_date' => '2026-06-26', 'fuel_level' => 93, 'service_category' => 'Public Works'],
            ['registration_number' => 'GV-1028', 'vehicle_type' => 'Bus', 'make' => 'Tata', 'model' => 'LP 909', 'manufacturing_year' => 2018, 'color' => 'White', 'vin' => 'MAT448008JH102028', 'engine_number' => 'CR4-1001028', 'fuel_type' => 'Diesel', 'fuel_capacity' => 150, 'technical_notes' => 'Community outreach bus.', 'registration_expiry' => '2026-10-28', 'revenue_license_expiry' => '2026-10-28', 'insurance_policy' => 'GIC-MV-1028', 'insurance_provider' => 'Allianz Lanka', 'assignment' => 'Community Relations Unit', 'status' => 'available', 'last_service_date' => '2026-05-09', 'fuel_level' => 55, 'service_category' => 'Community Services'],
            ['registration_number' => 'GV-1029', 'vehicle_type' => 'Van', 'make' => 'Nissan', 'model' => 'NV350', 'manufacturing_year' => 2021, 'color' => 'Silver', 'vin' => 'E26-1029000000001', 'engine_number' => 'QR25-1001029', 'fuel_type' => 'Petrol', 'fuel_capacity' => 65, 'technical_notes' => 'Records digitization support vehicle.', 'registration_expiry' => '2027-03-18', 'revenue_license_expiry' => '2027-03-18', 'insurance_policy' => 'GIC-MV-1029', 'insurance_provider' => 'People’s Insurance', 'assignment' => 'Digital Services Unit', 'status' => 'available', 'last_service_date' => '2026-06-07', 'fuel_level' => 69, 'service_category' => 'Technical Services'],
            ['registration_number' => 'GV-1030', 'vehicle_type' => 'SUV', 'make' => 'Ford', 'model' => 'Everest', 'manufacturing_year' => 2022, 'color' => 'Black', 'vin' => 'MNAAXXMAWANC102030', 'engine_number' => 'P5AT-1001030', 'fuel_type' => 'Diesel', 'fuel_capacity' => 80, 'technical_notes' => 'Emergency coordination vehicle.', 'registration_expiry' => '2027-06-30', 'revenue_license_expiry' => '2027-06-30', 'insurance_policy' => 'GIC-MV-1030', 'insurance_provider' => 'Fairfirst Insurance', 'assignment' => 'Emergency Operations Centre', 'status' => 'available', 'last_service_date' => '2026-06-21', 'fuel_level' => 87, 'service_category' => 'Emergency Response'],
        ];
    }
}
