const escapeHtml = (value) => String(value ?? "-").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const text = (value) => escapeHtml(value || "-");

export function generateDriverDirectoryPdf(drivers) {
  if (!Array.isArray(drivers) || drivers.length === 0) throw new Error("Select at least one driver to export.");
  const generatedAt = new Intl.DateTimeFormat("en-LK", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Colombo" }).format(new Date());
  const perPage = 8;
  const pages = Array.from({ length: Math.ceil(drivers.length / perPage) }, (_, index) => drivers.slice(index * perPage, (index + 1) * perPage));
  const sheets = pages.map((items, pageIndex) => `<div class="sheet"><div class="masthead"><div class="brand">Vehicle Management System</div><div class="sub">Chief Ministry&nbsp;&nbsp; | &nbsp;&nbsp;Dakshinapaya, Labuduwa, Galle</div></div><div class="title"><div><h1>Driver Details Records</h1><p>Official driver identity, licence, availability, and allocation report</p></div><span class="badge">DRIVER REPORT</span></div>${pageIndex === 0 ? `<div class="summary"><div><span>SELECTED DRIVERS</span><strong>${drivers.length}</strong></div><div><span>AVAILABLE</span><strong>${drivers.filter((driver) => driver.status === "Available").length}</strong></div><div><span>ASSIGNED VEHICLES</span><strong>${drivers.filter((driver) => driver.registration).length}</strong></div></div>` : ""}<h2>Driver Directory Details</h2><table><thead><tr><th>Driver / NIC</th><th>Contact / Blood</th><th>Licence</th><th>Licence Expiry</th><th>Status</th><th>Allocated Vehicle</th></tr></thead><tbody>${items.map((driver) => `<tr><td><strong>${text(driver.fullName)}</strong><small>${text(driver.id)} | ${text(driver.nic)}</small></td><td>${text(driver.contactNumber)}<small>Blood: ${text(driver.bloodGroup)}</small></td><td>${text(driver.licenceNumber)}<small>Type: ${text(driver.licenceType)}</small></td><td>${text(driver.licenceRenewalDate)}</td><td>${text(driver.status)}<small>Duty: ${text(driver.dutyStatus)}</small></td><td>${text(driver.vehicle)}<small>${text(driver.registration)}</small></td></tr>`).join("")}</tbody></table>${pageIndex === pages.length - 1 ? `<div class="reference"><strong>Document Reference</strong>Driver Details Records &nbsp;|&nbsp; ${drivers.length} selected driver${drivers.length === 1 ? "" : "s"} &nbsp;|&nbsp; Generated ${escapeHtml(generatedAt)} by the Vehicle Management System</div>` : ""}<div class="footer"><span>Chief Ministry - Southern Province</span><span>Page ${pageIndex + 1} of ${pages.length}</span></div></div>`).join("");
  const printWindow = window.open("", "_blank");
  if (!printWindow) throw new Error("The PDF window was blocked. Allow pop-ups and try again.");
  printWindow.opener = null;
  printWindow.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Driver Details Records</title><style>
  @page{size:A4 landscape;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#eef1f5;color:#172033;font-family:Arial,sans-serif}.sheet{position:relative;width:297mm;min-height:210mm;margin:0 auto 8mm;padding:40mm 14mm 20mm;background:#fff;page-break-after:always;overflow:hidden}.sheet:last-child{page-break-after:auto}.masthead{position:absolute;top:0;left:0;right:0;height:29mm;border-bottom:2mm solid #2c79c7;background:#0b2f5b;color:#fff;text-align:center;padding-top:12mm}.brand{font-size:18pt;font-weight:700}.sub{margin-top:2.5mm;color:#d6e7f7;font-size:8.8pt}.title{display:flex;align-items:center;justify-content:space-between;margin-bottom:5mm}h1{margin:0;font-size:21pt}.title p{margin:1.5mm 0 0;color:#647084;font-size:9pt}.badge{border-radius:20px;background:#e8f3ff;color:#1558a6;padding:3mm 6mm;font-size:8pt;font-weight:700}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:4mm;margin-bottom:5mm}.summary div{border:.2mm solid #d6e0ea;border-radius:2mm;background:#f8fafc;padding:3mm 4mm}.summary span{display:block;margin-bottom:1mm;color:#647084;font-size:6.5pt;font-weight:700}.summary strong{color:#0b2f5b;font-size:12pt}h2{margin:0 0 2.5mm;border-left:1.4mm solid #1558a6;padding:1.5mm 0 1.5mm 3mm;color:#0b2f5b;font-size:11.5pt;text-transform:uppercase}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:7.8pt}th{background:#0b2f5b;color:#fff;padding:2.7mm 2mm;text-align:left;font-size:6.7pt;text-transform:uppercase}th:nth-child(1){width:20%}th:nth-child(2){width:16%}th:nth-child(3){width:16%}th:nth-child(4){width:13%}th:nth-child(5){width:14%}th:nth-child(6){width:21%}td{border:.2mm solid #d6e0ea;padding:3mm 2mm;overflow-wrap:anywhere}tbody tr:nth-child(even){background:#f8fafc}td strong,td small{display:block}td small{margin-top:1.2mm;color:#647084;font-size:6.8pt}.reference{margin-top:5mm;border-radius:2mm;background:#edf5fd;padding:4mm;color:#647084;font-size:7.3pt}.reference strong{display:block;margin-bottom:1.5mm;color:#0b2f5b;font-size:8pt}.footer{position:absolute;right:14mm;bottom:7mm;left:14mm;display:flex;justify-content:space-between;border-top:.2mm solid #d6e0ea;padding-top:3mm;color:#647084;font-size:7.5pt}@media screen{.sheet{box-shadow:0 8px 30px rgba(15,23,42,.16)}}@media print{html,body{background:#fff}.sheet{margin:0;box-shadow:none}}
  </style></head><body>${sheets}<script>window.addEventListener("load",()=>{setTimeout(()=>window.print(),250)});<\/script></body></html>`);
  printWindow.document.close();
}
