const escapeHtml = (value) => String(value ?? "-").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const value = (item) => escapeHtml(item || "-");
const field = (name, item) => `<div class="field"><span>${escapeHtml(name)}</span><strong>${value(item)}</strong></div>`;

export function generateDriverDetailsPdf(driver) {
  if (!driver) throw new Error("Driver details are unavailable.");
  const generatedAt = new Intl.DateTimeFormat("en-LK", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Colombo" }).format(new Date());
  const identity = [field("Driver ID", driver.id), field("Full name", driver.fullName), field("Date of birth", driver.dateOfBirth), field("NIC", driver.nic), field("Blood group", driver.bloodGroup), field("Contact number", driver.contactNumber), field("Address", driver.address), field("Duty status", driver.dutyStatus)].join("");
  const licence = [field("Licence number", driver.licenceNumber), field("Licence type", driver.licenceType), field("Licence expiry date", driver.licenceRenewalDate), field("Operational status", driver.status)].join("");
  const allocation = [field("Allocated vehicle", driver.vehicle), field("Vehicle registration", driver.registration)].join("");
  const printWindow = window.open("", "_blank");
  if (!printWindow) throw new Error("The PDF window was blocked. Allow pop-ups and try again.");
  printWindow.opener = null;
  printWindow.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${value(driver.id)} - Driver Record</title><style>
  @page{size:A4;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#eef1f5;color:#172033;font-family:Arial,sans-serif}.sheet{position:relative;width:210mm;min-height:297mm;margin:0 auto;padding:48mm 18mm 21mm;background:#fff;overflow:hidden}.masthead{position:absolute;top:0;left:0;right:0;display:flex;height:34mm;flex-direction:column;align-items:center;justify-content:center;border-bottom:2.2mm solid #2c79c7;background:#0b2f5b;color:#fff;text-align:center}.brand{font-size:18pt;font-weight:700;line-height:1}.sub{margin-top:3mm;color:#d6e7f7;font-size:8.8pt}.title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8mm}h1{margin:0;font-size:22pt}.title p{margin:2mm 0 0;color:#647084;font-size:9pt}.badge{border-radius:20px;background:#e8f3ff;color:#1558a6;padding:3mm 6mm;font-size:8pt;font-weight:700;text-transform:uppercase}section{margin-bottom:7mm}h2{margin:0 0 3mm;border-left:1.4mm solid #1558a6;padding:2mm 0 2mm 3mm;color:#0b2f5b;font-size:11.5pt;text-transform:uppercase}.grid{display:grid;grid-template-columns:1fr 1fr;border:.2mm solid #d6e0ea;border-bottom:0}.field{min-height:14mm;padding:3mm;border-bottom:.2mm solid #d6e0ea}.field:nth-child(4n+3),.field:nth-child(4n+4){background:#f8fafc}.field:nth-child(odd){border-right:.2mm solid #d6e0ea}.field span{display:block;margin-bottom:1.5mm;color:#647084;font-size:6.4pt;font-weight:700;text-transform:uppercase;letter-spacing:.35px}.field strong{display:block;white-space:pre-wrap;overflow-wrap:anywhere;font-size:8.5pt;line-height:1.25}.reference{margin-top:9mm;border-radius:3mm;background:#edf5fd;padding:5mm 4mm;color:#647084;font-size:7.4pt}.reference strong{display:block;margin-bottom:2mm;color:#0b2f5b;font-size:8pt}.footer{position:absolute;right:18mm;bottom:8mm;left:18mm;display:flex;justify-content:space-between;border-top:.2mm solid #d6e0ea;padding-top:4mm;color:#647084;font-size:7.5pt}@media screen{.sheet{box-shadow:0 8px 30px rgba(15,23,42,.16)}}@media print{html,body{background:#fff}.sheet{margin:0;box-shadow:none}}
  </style></head><body><div class="sheet"><div class="masthead"><div class="brand">Vehicle Management System</div><div class="sub">Chief Ministry&nbsp;&nbsp; | &nbsp;&nbsp;Dakshinapaya, Labuduwa, Galle</div></div><div class="title"><div><h1>Driver Details Record</h1><p>${value(driver.id)} &nbsp;|&nbsp; Official driver registration and allocation record</p></div><span class="badge">${value(driver.dutyStatus)}</span></div><section><h2>Personal and Employment Information</h2><div class="grid">${identity}</div></section><section><h2>Driving Licence Information</h2><div class="grid">${licence}</div></section><section><h2>Vehicle Allocation</h2><div class="grid">${allocation}</div></section><div class="reference"><strong>Document Reference</strong>Driver Details Record &nbsp;|&nbsp; ${value(driver.id)} &nbsp;|&nbsp; Generated ${escapeHtml(generatedAt)} by the Vehicle Management System</div><div class="footer"><span>Chief Ministry - Southern Province</span><span>Page 1 of 1</span></div></div><script>window.addEventListener("load",()=>{setTimeout(()=>window.print(),250)});</script></body></html>`);
  printWindow.document.close();
}
