const escapeHtml = (value) => String(value ?? "-").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const text = (value) => escapeHtml(value || "-");
const money = (value) => Number(value || 0).toLocaleString("en-LK", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const label = (value) => text(value ? String(value).replaceAll("_", " ") : "Not recorded");
const field = (name, value) => `<div class="field"><span>${escapeHtml(name)}</span><strong>${text(value)}</strong></div>`;
const section = (title, fields) => `<section><h2>${escapeHtml(title)}</h2><div class="grid">${fields.join("")}</div></section>`;
const chunks = (items, size = 14) => Array.from({ length: Math.ceil(items.length / size) }, (_, index) => items.slice(index * size, (index + 1) * size));

export function generateVehicleDetailsPdf(vehicle) {
  if (!vehicle) throw new Error("Vehicle details are unavailable.");
  const generatedAt = new Intl.DateTimeFormat("en-LK", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Colombo" }).format(new Date());
  const registration = vehicle.registration_number || "Vehicle";
  const recordGroups = [
    { title: "Service Records", items: vehicle.service_details || [], columns: ["Date", "Service Type", "Cost (LKR)"], cells: (item) => [item.service_date, item.service_type, money(item.cost)] },
    { title: "Repair Records", items: vehicle.repair_details || [], columns: ["Date", "Repair Type", "Cost (LKR)"], cells: (item) => [item.repair_date, item.repair_type, money(item.cost)] },
    { title: "Fuel Records", items: vehicle.fuel_details || [], columns: ["Date", "Fuel Type", "Capacity (L)", "Cost (LKR)"], cells: (item) => [item.date, item.fuel_type, money(item.capacity), money(item.cost)] },
  ];
  const recordPages = recordGroups.flatMap((group) => chunks(group.items).map((items, part) => ({ ...group, items, part })));
  const totalPages = 1 + recordPages.length;
  const masthead = `<div class="masthead"><div class="brand">Vehicle Management System</div><div class="sub">Chief Ministry&nbsp;&nbsp; | &nbsp;&nbsp;Dakshinapaya, Labuduwa, Galle</div></div>`;
  const footer = (page) => `<div class="footer"><span>Chief Ministry - Southern Province</span><span>Page ${page} of ${totalPages}</span></div>`;
  const overview = `<div class="sheet">${masthead}<div class="title"><div><h1>Vehicle Details Record</h1><p>${text(registration)} &nbsp;|&nbsp; Official fleet registration and compliance record</p></div><span class="badge">${label(vehicle.status)}</span></div>
    ${section("Vehicle Identification", [field("Registration number", vehicle.registration_number), field("Vehicle type", vehicle.vehicle_type), field("Make", vehicle.make), field("Model", vehicle.model), field("Manufacturing year", vehicle.manufacturing_year), field("Colour", vehicle.color), field("VIN", vehicle.vin), field("Engine number", vehicle.engine_number)])}
    ${section("Operational Information", [field("Status", vehicle.status), field("Assignment", vehicle.assignment), field("Seat capacity", vehicle.seat_capacity), field("Fuel level", `${vehicle.fuel_level ?? 0}%`), field("Fuel type", vehicle.fuel_type), field("Fuel capacity", vehicle.fuel_capacity ? `${vehicle.fuel_capacity} L` : "-"), field("Fuel efficiency", vehicle.fuel_efficiency ? `${vehicle.fuel_efficiency} ${vehicle.fuel_efficiency_unit || "km/l"}` : "-"), field("Last service date", vehicle.last_service_date), field("Service category", vehicle.service_category)])}
    ${section("Compliance and Insurance", [field("Registration expiry", vehicle.registration_expiry), field("Revenue licence expiry", vehicle.revenue_license_expiry), field("Insurance policy", vehicle.insurance_policy), field("Insurance provider", vehicle.insurance_provider), field("Technical notes", vehicle.technical_notes), field("Total service cost", `LKR ${money(vehicle.service_total_cost)}`)])}
    <div class="reference"><strong>Document Reference</strong>Vehicle Details Record &nbsp;|&nbsp; ${text(registration)} &nbsp;|&nbsp; Generated ${escapeHtml(generatedAt)}</div>${footer(1)}</div>`;
  const detailSheets = recordPages.map((group, index) => `<div class="sheet">${masthead}<div class="title"><div><h1>${group.title}</h1><p>${text(registration)} &nbsp;|&nbsp; ${group.part ? `Continuation ${group.part + 1}` : "Complete vehicle history"}</p></div><span class="badge">FLEET RECORD</span></div><h2>${group.title}</h2><table><thead><tr><th>No.</th>${group.columns.map((column) => `<th>${column}</th>`).join("")}</tr></thead><tbody>${group.items.map((item, rowIndex) => `<tr><td>${group.part * 14 + rowIndex + 1}</td>${group.cells(item).map((cell) => `<td>${text(cell)}</td>`).join("")}</tr>`).join("")}</tbody><tfoot><tr><td colspan="${group.columns.length}">${group.title} total entries</td><td>${group.items.length}</td></tr></tfoot></table>${footer(index + 2)}</div>`).join("");
  const printWindow = window.open("", "_blank");
  if (!printWindow) throw new Error("The PDF window was blocked. Allow pop-ups and try again.");
  printWindow.opener = null;
  printWindow.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${text(registration)} - Vehicle Record</title><style>
  @page{size:A4;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#eef1f5;color:#172033;font-family:Arial,sans-serif}.sheet{position:relative;width:210mm;min-height:297mm;margin:0 auto 8mm;padding:48mm 18mm 21mm;background:#fff;page-break-after:always;overflow:hidden}.sheet:last-child{page-break-after:auto}.masthead{position:absolute;top:0;left:0;right:0;display:flex;height:34mm;flex-direction:column;align-items:center;justify-content:center;border-bottom:2.2mm solid #2c79c7;background:#0b2f5b;color:#fff;text-align:center}.brand{font-size:18pt;font-weight:700}.sub{margin-top:3mm;color:#d6e7f7;font-size:8.8pt}.title{display:flex;justify-content:space-between;align-items:center;margin-bottom:7mm}h1{margin:0;font-size:22pt}.title p{margin:2mm 0 0;color:#647084;font-size:9pt}.badge{border-radius:20px;background:#e8f3ff;color:#1558a6;padding:3mm 6mm;font-size:8pt;font-weight:700;text-transform:uppercase}section{margin-bottom:5mm}h2{margin:0 0 2.5mm;border-left:1.4mm solid #1558a6;padding:1.6mm 0 1.6mm 3mm;color:#0b2f5b;font-size:11pt;text-transform:uppercase}.grid{display:grid;grid-template-columns:1fr 1fr;border:.2mm solid #d6e0ea;border-bottom:0}.field{min-height:11.5mm;padding:2.4mm 3mm;border-bottom:.2mm solid #d6e0ea}.field:nth-child(4n+3),.field:nth-child(4n+4){background:#f8fafc}.field:nth-child(odd){border-right:.2mm solid #d6e0ea}.field span{display:block;margin-bottom:1.2mm;color:#647084;font-size:6.3pt;font-weight:700;text-transform:uppercase}.field strong{display:block;white-space:pre-wrap;overflow-wrap:anywhere;font-size:8.1pt}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:8pt}th{background:#0b2f5b;color:#fff;padding:3mm 2mm;text-align:left;font-size:6.8pt;text-transform:uppercase}th:first-child{width:9%}td{border:.2mm solid #d6e0ea;padding:3mm 2mm;overflow-wrap:anywhere}tbody tr:nth-child(even){background:#f8fafc}tfoot td{background:#edf5fd;color:#0b2f5b;font-weight:700}.reference{margin-top:5mm;border-radius:2mm;background:#edf5fd;padding:4mm;color:#647084;font-size:7.2pt}.reference strong{display:block;margin-bottom:1.3mm;color:#0b2f5b;font-size:8pt}.footer{position:absolute;right:18mm;bottom:8mm;left:18mm;display:flex;justify-content:space-between;border-top:.2mm solid #d6e0ea;padding-top:4mm;color:#647084;font-size:7.5pt}@media screen{.sheet{box-shadow:0 8px 30px rgba(15,23,42,.16)}}@media print{html,body{background:#fff}.sheet{margin:0;box-shadow:none}}
  </style></head><body>${overview}${detailSheets}<script>window.addEventListener("load",()=>{setTimeout(()=>window.print(),250)});</script></body></html>`);
  printWindow.document.close();
}
