// Shared UI vocabulary used by the page translator. Longer phrases are applied
// before individual words so existing JSX can be localized without duplicating
// translation logic in every role-specific screen.
export const pageTranslations = {
  si: {
    "starting location":"ආරම්භක ස්ථානය","ending location":"අවසාන ස්ථානය","select starting location":"ආරම්භක ස්ථානය තෝරන්න","select ending location":"අවසාන ස්ථානය තෝරන්න","calculated distance":"ගණනය කළ දුර","calculated automatically":"ස්වයංක්‍රීයව ගණනය කරන ලදී","driving route":"රියදුරු මාර්ගය","calculating feasible route":"සුදුසු මාර්ගය ගණනය කරමින්","a feasible driving route could not be calculated for these locations":"මෙම ස්ථාන අතර සුදුසු රියදුරු මාර්ගයක් ගණනය කළ නොහැකි විය","select both locations to calculate distance":"දුර ගණනය කිරීමට ස්ථාන දෙකම තෝරන්න","click the map to place the selected point":"තෝරාගත් ස්ථානය සලකුණු කිරීමට සිතියම ක්ලික් කරන්න","type or select the starting point on the map":"ආරම්භක ස්ථානය ටයිප් කරන්න හෝ සිතියමෙන් තෝරන්න","type or select the ending point on the map":"අවසාන ස්ථානය ටයිප් කරන්න හෝ සිතියමෙන් තෝරන්න","find on map":"සිතියමේ සොයන්න","finding location":"ස්ථානය සොයමින්","no matching location found in sri lanka":"ශ්‍රී ලංකාව තුළ ගැළපෙන ස්ථානයක් හමු නොවීය","unable to find that location. please select it on the map":"එම ස්ථානය සොයාගත නොහැක. කරුණාකර සිතියමෙන් තෝරන්න","map location selector":"සිතියම් ස්ථාන තේරීම","location to select":"තේරිය යුතු ස්ථානය",
    "review pending requests":"පොරොත්තු ඉල්ලීම් සමාලෝචනය කරන්න",
    "department overview":"දෙපාර්තමේන්තු දළ විශ්ලේෂණය","welcome back":"සාදරයෙන් පිළිගන්නවා","here are your department's vehicle requests":"මෙන්න ඔබගේ දෙපාර්තමේන්තුවේ වාහන ඉල්ලීම්","vehicle requests awaiting department review":"දෙපාර්තමේන්තු සමාලෝචනය අපේක්ෂාවෙන් පවතින වාහන ඉල්ලීම්","there are no pending requests for your department":"ඔබගේ දෙපාර්තමේන්තුව සඳහා පොරොත්තු ලේඛනයේ ඇති ඉල්ලීම් කිසිවක් නැත","monitor and manage your vehicle allocation requests":"ඔබගේ වාහන වෙන්කිරීමේ ඉල්ලීම් නිරීක්ෂණය සහ කළමනාකරණය කරන්න","search & filters":"සෙවීම් සහ පෙරහන්","locate reviewed requests using live backend records":"සජීවී පසුපෙළ (Backend) වාර්තා භාවිතයෙන් සමාලෝචනය කරන ලද ඉල්ලීම් සොයා ගන්න","review pending request":"පොරොත්තු ඉල්ලීම් සමාලෝචනය කරන්න","historical records":"ඉතිහාස වාර්තා","request archive":"ඉල්ලීම් ලේඛනාගාරය","reviewed vehicle requests from your department":"ඔබගේ දෙපාර්තමේන්තුවෙන් සමාලෝචනය කරන ලද වාහන ඉල්ලීම්","employee name":"සේවකයාගේ නම","date recommended by":"නිර්දේශ කරන ලද දිනය සහ නිර්දේශකයා","decision date":"තීරණය ගත් දිනය","all decisions":"සියලුම තීරණ","recommend":"නිර්දේශ කරන්න","fleet management":"වාහන ඇණිය කළමනාකරණය","manage and monitor all government fleet assets from a single location":"සියලුම රාජ්‍ය වාහන වත්කම් එකම ස්ථානයක සිට කළමනාකරණය සහ නිරීක්ෂණය කරන්න","repairs":"අලුත්වැඩියාවන්","last service":"අවසන් වරට සේවා (Service) කරන ලද දිනය","fuel level":"ඉන්ධන මට්ටම","use update to edit a vehicle":"වාහනයක විස්තර යාවත්කාලීන කිරීමට 'යාවත්කාලීන කරන්න' (Update) භාවිත කරන්න","register drivers and maintain their identity, licence, allocation, and status details":"රියදුරන් ලියාපදිංචි කර ඔවුන්ගේ අනන්‍යතාවය, රියදුරු බලපත්‍රය, වෙන්කිරීම් සහ සේවා තත්ත්වය පිළිබඳ විස්තර පවත්වාගෙන යන්න","registered drivers":"ලියාපදිංචි රියදුරන්","19 driver records":"රියදුරු වාර්තා 19ක්","driver id":"රියදුරු හැඳුනුම් අංකය","driver name":"රියදුරුගේ නම","nic - (national identity card)":"ජාතික හැඳුනුම්පත් අංකය (NIC)","nic":"ජාතික හැඳුනුම්පත් අංකය (NIC)","contact number":"සම්බන්ධ කර ගැනීමේ අංකය","licence type":"රියදුරු බලපත්‍ර වර්ගය","licence expire date":"රියදුරු බලපත්‍රයේ වලංගු කාලය අවසන් වන දිනය","allocated vehicle":"වෙන් කරන ලද වාහනය","on trip":"ගමනක යෙදී ඇත",
    "fleet maintenance center":"වාහන නඩත්තු මධ්‍යස්ථානය","service & maintenance records":"සේවා සහ නඩත්තු වාර්තා","monitor fleet health, maintenance schedules, vendor assignments, and service performance":"වාහනවල තත්ත්වය, නඩත්තු කාලසටහන්, අදාළ සැපයුම්කරුවන් සහ සේවා කාර්යසාධනය නිරීක්ෂණය කරන්න","overdue":"පැණවූ කාලය ඉක්මවා ඇති","savings":"ඉතිරිකිරීම්","vendor":"සැපයුම්කරු / සේවා සපයන්නා","due date":"නියමිත දිනය","showing 3 maintenance schedules":"නඩත්තු කාලසටහන් 3ක් පෙන්වයි","schedule service":"සේවාවක් කාලසටහන්ගත කරන්න","fleet inventory":"වාහන තොග ලේඛනය","full fleet inventory and specifications":"සම්පූර්ණ වාහන ලේඛනය සහ පිරිවිතරයන්","30 matching vehicles":"ගැළපෙන වාහන 30ක්","vehicle name":"වාහනයේ නම","register number":"ලියාපදිංචි අංකය","fuel type":"ඉන්ධන වර්ගය","fuel capacity":"ඉන්ධන ධාරිතාවය","seat capacity":"ආසන ධාරිතාවය","showing all 30 matching vehicles. scroll the inventory to view the complete list":"ගැළපෙන වාහන 30ම පෙන්වයි. සම්පූර්ණ ලැයිස්තුව බැලීමට ලේඛනය පහළට අනුචලනය (Scroll) කරන්න","view driver identity, licence, contact, vehicle allocation, and availability information":"රියදුරු අනන්‍යතාවය, බලපත්‍රය, සම්බන්ධතා තොරතුරු, වාහන වෙන්කිරීම් සහ රියදුරු පහසුවෙන් සම්බන්ධ කරගත හැකි බව (Availability) පිළිබඳ තොරතුරු බලන්න","monitor fuel consumption, expenses, efficiency, and vehicle fuel transaction records":"ඉන්ධන පරිභෝජනය, වියදම්, කාර්යක්ෂමතාවය සහ වාහනවල ඉන්ධන ගනුදෙනු වාර්තා නිරීක්ෂණය කරන්න","pending final approvals":"අවසන් අනුමැතිය අපේක්ෂාවෙන් පවතින","senior assistance secretary":"ජ්‍යෙෂ්ඨ සහකාර ලේකම්","review requests that have completed vehicle and driver allocation":"වාහන සහ රියදුරන් වෙන්කිරීමේ කටයුතු අවසන් කරන ලද ඉල්ලීම් සමාලෝචනය කරන්න","request id":"ඉල්ලීම් අංකය","requester":"ඉල්ලුම්කරු","journey details":"ගමන් විස්තර","available vehicles":"භාවිතයට ගත හැකි වාහන","monthly cost analysis":"මාසික වියදම් විශ්ලේෂණය","fuel and maintenance expenditure by month":"මාසිකව ඉන්ධන සහ නඩත්තු සඳහා වූ වියදම්",
    "welcome back, {name}":"සාදරයෙන් පිළිගන්නවා, {name}","here is what's happening with your transport requests today":"මෙන්න ඔබගේ අද දින ප්‍රවාහන ඉල්ලීම්වල වත්මන් තත්ත්වය","pending requests":"පොරොත්තු ලේඛනයේ ඇති ඉල්ලීම්","official transport":"නිල ප්‍රවාහන සේවා","create new vehicle request":"නව වාහන ඉල්ලීමක් ඇතුළත් කරන්න","please fill in the details below to request a vehicle for official business":"නිල කටයුත්තක් සඳහා වාහනයක් වෙන්කරවා ගැනීමට කරුණාකර පහත විස්තර සම්පූර්ණ කරන්න","draft id":"කෙටුම්පත් අංකය","trip information":"ගමන් විස්තර","where and when are you travelling":"ඔබ ගමන් කරන්නේ කොහේටද සහ කවදාද","purpose of trip":"ගමනේ අරමුණ","regional site inspection":"ප්‍රාදේශීය ස්ථාන පරීක්ෂාව","administrative office":"පරිපාලන කාර්යාලය","departure date & time":"පිටත්වන දිනය සහ වේලාව","passenger details":"මගීන්ගේ විස්තර","who else is travelling with you":"ඔබ සමඟ තව කවුරුන් ගමන් කරනවාද","total count":"මුළු එකතුව","passenger names":"මගීන්ගේ නම්","enter names":"නම් ඇතුළත් කරන්න","attachments":"අමුණා ඇති ලිපිගොනු","upload supporting documents":"අදාළ ලියකියවිලි උඩුගත කරන්න","click to upload or drag & drop":"උඩුගත කිරීමට ක්ලික් කරන්න නැතහොත් ඇදගෙන අවුත් අතහරින්න","selected":"තෝරා ගන්නා ලදී","save draft":"කෙටුම්පත සුරකින්න","submit request":"ඉල්ලීම ඉදිරිපත් කරන්න","submitting":"ඉදිරිපත් කරමින් පවතී","vehicle request submitted successfully":"වාහන ඉල්ලීම සාර්ථකව ඉදිරිපත් කරන ලදී","unable to submit the request. please try again":"ඉල්ලීම ඉදිරිපත් කිරීමට නොහැකි විය. කරුණාකර නැවත උත්සාහ කරන්න","unable to load request statistics":"ඉල්ලීම් පිළිබඳ දත්ත/සංඛ්‍යාලේඛන ලබා ගැනීමට නොහැකි විය","expected return":"නැවත පැමිණීමට බලාපොරොත්තු වන දිනය/වේලාව","approved":"අනුමත කරන ලද","rejected":"ප්‍රතික්ෂේප කරන ලද",
    "fleet operations overview":"වාහන මෙහෙයුම් දළ විශ්ලේෂණය","monitoring vehicles across government departments":"රජයේ දෙපාර්තමේන්තු පුරා වාහන අධීක්ෂණය කිරීම","total vehicles":"මුළු වාහන","available now":"දැනට ලබාගත හැකි","unavailable now":"දැනට ලබාගත නොහැකි","registered fleet":"ලියාපදිංචි වාහන සංචිතය","ready for allocation":"වෙන් කිරීම සඳහා සූදානම්","currently unavailable":"දැනට ලබාගත නොහැක","in maintenance":"නඩත්තු වෙමින්","fuel cost":"ඉන්ධන පිරිවැය","no stored fuel transactions":"සුරැකි ඉන්ධන ගනුදෙනු නොමැත","service costs":"සේවා පිරිවැය","recorded service spending":"සටහන් කළ සේවා වියදම්","repair expense":"අලුත්වැඩියා වියදම","recorded repair spending":"සටහන් කළ අලුත්වැඩියා වියදම්","fleet status overview":"වාහන සංචිතයේ තත්ත්ව දළ විශ්ලේෂණය","real-time availability of government vehicles":"රජයේ වාහනවල තත්කාලීන ලබාගත හැකි බව","no vehicles are registered in the fleet":"වාහන සංචිතයේ කිසිදු වාහනයක් ලියාපදිංචි කර නැත","retry":"නැවත උත්සාහ කරන්න",
    "vehicle management system":"වාහන කළමනාකරණ පද්ධතිය","chief ministry":"ප්‍රධාන අමාත්‍යාංශය","government fleet":"රජයේ වාහන සංචිතය","sri lanka":"ශ්‍රී ලංකාව",
    "request history":"ඉල්ලීම් ඉතිහාසය","approved journeys":"අනුමත ගමන්","total approvals":"සියලු අනුමැති","pending approvals":"අපේක්ෂිත අනුමැති","pending recommendations":"අපේක්ෂිත නිර්දේශ","vehicle directory":"වාහන නාමාවලිය","driver directory":"රියදුරු නාමාවලිය","fuel management":"ඉන්ධන කළමනාකරණය","service records":"සේවා වාර්තා","repair records":"අලුත්වැඩියා වාර්තා","vehicle details":"වාහන විස්තර","driver details":"රියදුරු විස්තර","fuel records":"ඉන්ධන වාර්තා","user settings":"පරිශීලක සැකසුම්",
    "save changes":"වෙනස්කම් සුරකින්න","save vehicle":"වාහනය සුරකින්න","register new vehicle":"නව වාහනයක් ලියාපදිංචි කරන්න","back to directory":"නාමාවලියට ආපසු","view details":"විස්තර බලන්න","request details":"ඉල්ලීම් විස්තර","loading request details":"ඉල්ලීම් විස්තර පූරණය වෙමින්","not yet reviewed":"තවම සමාලෝචනය කර නැත","not reviewed":"සමාලෝචනය කර නැත","not recorded":"සටහන් කර නැත","not completed":"සම්පූර්ණ කර නැත","not available":"ලබා ගත නොහැක","not assigned":"පවරා නැත","not set":"සකසා නැත","no notes":"සටහන් නැත","no data available":"දත්ත නොමැත","no records found":"වාර්තා හමු නොවීය","no results found":"ප්‍රතිඵල හමු නොවීය","no previous journeys recorded for this driver":"මෙම රියදුරු සඳහා පෙර ගමන් සටහන් කර නැත",
    "department officer recommendation":"දෙපාර්තමේන්තු නිලධාරීගේ නිර්දේශය","recommendation notes":"නිර්දේශ සටහන්","previous journeys":"පෙර ගමන්","service details":"සේවා විස්තර","total service cost":"මුළු සේවා පිරිවැය","service date":"සේවා දිනය","service type":"සේවා වර්ගය","passenger count":"මගීන් ගණන","expected return":"නැවත පැමිණීමට බලාපොරොත්තු වන දිනය/වේලාව","departure time":"පිටත්වීමේ වේලාව","created at":"නිර්මාණය කළ දිනය","approved at":"අනුමත කළ දිනය","allocated at":"වෙන් කළ දිනය","submitted at":"ඉදිරිපත් කළ දිනය","finally approved by":"අවසානයේ අනුමත කළේ","allocated by":"වෙන් කළේ","submitted by":"ඉදිරිපත් කළේ","recommended at":"නිර්දේශ කළ දිනය","officer department":"නිලධාරියාගේ දෙපාර්තමේන්තුව",
    "sign in":"පිවිසෙන්න","sign up":"ලියාපදිංචි වන්න","forgot password":"මුරපදය අමතකද","reset password":"මුරපදය නැවත සකසන්න","email address":"විද්‍යුත් තැපැල් ලිපිනය","confirm password":"මුරපදය තහවුරු කරන්න","remember me":"මාව මතක තබා ගන්න","create account":"ගිණුමක් සාදන්න","already have an account":"දැනටමත් ගිණුමක් තිබේ","Pending Requests":"අපේක්ෂිත ඉල්ලීම්","Approved Requests":"අනුමත ඉල්ලීම්","Rejected Requests":"ප්‍රතික්ෂේපිත ඉල්ලීම්","Returned Requests":"ආපසු යැවූ ඉල්ලීම්","Completed Requests":"සම්පූර්ණ ඉල්ලීම්",
    dashboard:"උපකරණ පුවරුව",main:"ප්‍රධාන",details:"විස්තර",organization:"ආයතනය",reports:"වාර්තා",drivers:"රියදුරන්",logout:"ඉවත් වන්න",welcome:"සාදරයෙන් පිළිගනිමු",overview:"දළ විශ්ලේෂණය",analytics:"විශ්ලේෂණ",activity:"ක්‍රියාකාරකම්",notifications:"දැනුම්දීම්",settings:"සැකසුම්",profile:"පැතිකඩ",
    request:"ඉල්ලීම",requests:"ඉල්ලීම්",recommendation:"නිර්දේශය",recommendations:"නිර්දේශ",approval:"අනුමැතිය",approvals:"අනුමැති",journey:"ගමන",journeys:"ගමන්",trip:"ගමන",trips:"ගමන්",vehicle:"වාහනය",vehicles:"වාහන",driver:"රියදුරු",employee:"සේවක",officer:"නිලධාරී",department:"දෙපාර්තමේන්තුව",secretary:"ලේකම්",user:"පරිශීලක",
    pending:"අපේක්ෂිත",approved:"අනුමත කරන ලද",rejected:"ප්‍රතික්ෂේප කරන ලද",returned:"ආපසු යැවූ",completed:"සම්පූර්ණ",available:"ලබාගත හැකි",unavailable:"ලබාගත නොහැකි",active:"සක්‍රීය",inactive:"අක්‍රීය",maintenance:"නඩත්තු",allocated:"වෙන් කළ",assigned:"පවරන ලද",submitted:"ඉදිරිපත් කළ",recommended:"නිර්දේශිත",cancelled:"අවලංගු කළ",status:"තත්ත්වය",priority:"ප්‍රමුඛතාව",high:"ඉහළ",medium:"මධ්‍යම",low:"අඩු",
    name:"නම",email:"විද්‍යුත් තැපෑල",password:"මුරපදය",phone:"දුරකථනය",address:"ලිපිනය",role:"භූමිකාව",date:"දිනය",time:"වේලාව",from:"සිට",to:"දක්වා",origin:"ආරම්භය",destination:"ගමනාන්තය",purpose:"අරමුණ",passengers:"මගීන්",notes:"සටහන්",description:"විස්තරය",type:"වර්ගය",category:"කාණ්ඩය",registration:"ලියාපදිංචිය",number:"අංකය",model:"මාදිලිය",make:"නිෂ්පාදකයා",colour:"වර්ණය",color:"වර්ණය",year:"වසර",capacity:"ධාරිතාව",cost:"පිරිවැය",amount:"මුදල",total:"මුළු",fuel:"ඉන්ධන",service:"සේවාව",repair:"අලුත්වැඩියාව",history:"ඉතිහාසය",record:"වාර්තාව",records:"වාර්තා",database:"දත්ත ගබඩාව",information:"තොරතුරු",documents:"ලේඛන",documentation:"ලේඛනගත කිරීම",
    search:"සොයන්න",filter:"පෙරහන්",sort:"අනුපිළිවෙළ",all:"සියල්ල",view:"බලන්න",open:"විවෘත කරන්න",close:"වසන්න",back:"ආපසු",next:"ඊළඟ",previous:"පෙර",edit:"සංස්කරණය",update:"යාවත්කාලීන කරන්න",add:"එකතු කරන්න",remove:"ඉවත් කරන්න",delete:"මකන්න",save:"සුරකින්න",submit:"ඉදිරිපත් කරන්න",confirm:"තහවුරු කරන්න",cancel:"අවලංගු කරන්න",approve:"අනුමත කරන්න",reject:"ප්‍රතික්ෂේප කරන්න",return:"ආපසු යවන්න",allocate:"වෙන් කරන්න",assign:"පවරන්න",download:"බාගන්න",upload:"උඩුගත කරන්න",print:"මුද්‍රණය",refresh:"නැවුම් කරන්න",clear:"මකන්න",apply:"යොදන්න",action:"ක්‍රියාව",actions:"ක්‍රියා",
    loading:"පූරණය වෙමින්",saving:"සුරකිමින්",submitting:"ඉදිරිපත් කරමින් පවතී",processing:"සැකසෙමින්",success:"සාර්ථකයි",error:"දෝෂයකි",required:"අවශ්‍යයි",optional:"විකල්ප",yes:"ඔව්",no:"නැත",none:"කිසිවක් නැත",other:"වෙනත්",today:"අද",monthly:"මාසික",daily:"දෛනික",current:"වත්මන්",new:"නව",recent:"මෑත",select:"තෝරන්න",enter:"ඇතුළත් කරන්න",showing:"පෙන්වමින්",of:"න්",page:"පිටුව"
  },
  ta: {
    "starting location":"தொடக்க இடம்","ending location":"முடிவு இடம்","select starting location":"தொடக்க இடத்தைத் தேர்ந்தெடுக்கவும்","select ending location":"முடிவு இடத்தைத் தேர்ந்தெடுக்கவும்","calculated distance":"கணக்கிடப்பட்ட தூரம்","calculated automatically":"தானாகக் கணக்கிடப்பட்டது","driving route":"வாகனப் பாதை","calculating feasible route":"சாத்தியமான பாதை கணக்கிடப்படுகிறது","a feasible driving route could not be calculated for these locations":"இந்த இடங்களுக்கு இடையில் சாத்தியமான வாகனப் பாதையைக் கணக்கிட முடியவில்லை","select both locations to calculate distance":"தூரத்தைக் கணக்கிட இரண்டு இடங்களையும் தேர்ந்தெடுக்கவும்","click the map to place the selected point":"தேர்ந்தெடுத்த இடத்தைக் குறிக்க வரைபடத்தைக் கிளிக் செய்யவும்","type or select the starting point on the map":"தொடக்க இடத்தைத் தட்டச்சு செய்யவும் அல்லது வரைபடத்தில் தேர்ந்தெடுக்கவும்","type or select the ending point on the map":"முடிவு இடத்தைத் தட்டச்சு செய்யவும் அல்லது வரைபடத்தில் தேர்ந்தெடுக்கவும்","find on map":"வரைபடத்தில் தேடவும்","finding location":"இடம் தேடப்படுகிறது","no matching location found in sri lanka":"இலங்கையில் பொருந்தும் இடம் கிடைக்கவில்லை","unable to find that location. please select it on the map":"அந்த இடத்தைக் கண்டுபிடிக்க முடியவில்லை. வரைபடத்தில் தேர்ந்தெடுக்கவும்","map location selector":"வரைபட இடத் தேர்வி","location to select":"தேர்ந்தெடுக்க வேண்டிய இடம்",
    "fleet operations overview":"வாகனச் செயற்பாடுகளின் மேலோட்டம்","monitoring vehicles across government departments":"அரச திணைக்களங்களிலுள்ள வாகனங்களைக் கண்காணித்தல்","total vehicles":"மொத்த வாகனங்கள்","available now":"தற்போது கிடைப்பவை","unavailable now":"தற்போது கிடைக்காதவை","registered fleet":"பதிவுசெய்யப்பட்ட வாகனத் தொகுதி","ready for allocation":"ஒதுக்கீட்டிற்குத் தயார்","currently unavailable":"தற்போது கிடைக்கவில்லை","in maintenance":"பராமரிப்பில் உள்ளது","fuel cost":"எரிபொருள் செலவு","no stored fuel transactions":"சேமிக்கப்பட்ட எரிபொருள் பரிவர்த்தனைகள் இல்லை","service costs":"சேவைச் செலவுகள்","recorded service spending":"பதிவுசெய்யப்பட்ட சேவைச் செலவுகள்","repair expense":"திருத்தச் செலவு","recorded repair spending":"பதிவுசெய்யப்பட்ட திருத்தச் செலவுகள்","fleet status overview":"வாகனத் தொகுதி நிலை மேலோட்டம்","real-time availability of government vehicles":"அரச வாகனங்களின் நிகழ்நேரக் கிடைக்கும் நிலை","no vehicles are registered in the fleet":"வாகனத் தொகுதியில் வாகனங்கள் எதுவும் பதிவு செய்யப்படவில்லை","retry":"மீண்டும் முயல்க",
    "vehicle management system":"வாகன முகாமைத்துவ அமைப்பு","chief ministry":"முதன்மை அமைச்சு","government fleet":"அரச வாகனத் தொகுதி","sri lanka":"இலங்கை",
    "request history":"கோரிக்கை வரலாறு","approved journeys":"அங்கீகரிக்கப்பட்ட பயணங்கள்","total approvals":"அனைத்து அங்கீகாரங்கள்","pending approvals":"நிலுவை அங்கீகாரங்கள்","pending recommendations":"நிலுவைப் பரிந்துரைகள்","vehicle directory":"வாகனப் பட்டியல்","driver directory":"சாரதிப் பட்டியல்","fuel management":"எரிபொருள் முகாமைத்துவம்","service records":"சேவைப் பதிவுகள்","repair records":"திருத்தப் பதிவுகள்","vehicle details":"வாகன விபரங்கள்","driver details":"சாரதி விபரங்கள்","fuel records":"எரிபொருள் பதிவுகள்","user settings":"பயனர் அமைப்புகள்",
    "save changes":"மாற்றங்களைச் சேமிக்கவும்","save vehicle":"வாகனத்தைச் சேமிக்கவும்","register new vehicle":"புதிய வாகனத்தைப் பதிவு செய்யவும்","back to directory":"பட்டியலுக்குத் திரும்பவும்","view details":"விபரங்களைப் பார்க்கவும்","request details":"கோரிக்கை விபரங்கள்","loading request details":"கோரிக்கை விபரங்கள் ஏற்றப்படுகின்றன","not yet reviewed":"இன்னும் பரிசீலிக்கப்படவில்லை","not reviewed":"பரிசீலிக்கப்படவில்லை","not recorded":"பதிவு செய்யப்படவில்லை","not completed":"முடிக்கப்படவில்லை","not available":"கிடைக்கவில்லை","not assigned":"ஒதுக்கப்படவில்லை","not set":"அமைக்கப்படவில்லை","no notes":"குறிப்புகள் இல்லை","no data available":"தரவு இல்லை","no records found":"பதிவுகள் கிடைக்கவில்லை","no results found":"முடிவுகள் கிடைக்கவில்லை","no previous journeys recorded for this driver":"இந்தச் சாரதிக்கு முந்தைய பயணங்கள் பதிவு செய்யப்படவில்லை",
    "department officer recommendation":"திணைக்கள அலுவலரின் பரிந்துரை","recommendation notes":"பரிந்துரைக் குறிப்புகள்","previous journeys":"முந்தைய பயணங்கள்","service details":"சேவை விபரங்கள்","total service cost":"மொத்த சேவைச் செலவு","service date":"சேவைத் திகதி","service type":"சேவை வகை","passenger count":"பயணிகள் எண்ணிக்கை","expected return":"எதிர்பார்க்கப்படும் திரும்புதல்","departure time":"புறப்படும் நேரம்","created at":"உருவாக்கிய நேரம்","approved at":"அங்கீகரித்த நேரம்","allocated at":"ஒதுக்கிய நேரம்","submitted at":"சமர்ப்பித்த நேரம்","finally approved by":"இறுதியாக அங்கீகரித்தவர்","allocated by":"ஒதுக்கியவர்","submitted by":"சமர்ப்பித்தவர்","recommended at":"பரிந்துரைத்த நேரம்","officer department":"அலுவலரின் திணைக்களம்",
    "sign in":"உள்நுழையவும்","sign up":"பதிவு செய்யவும்","forgot password":"கடவுச்சொல் மறந்துவிட்டதா","reset password":"கடவுச்சொல்லை மீட்டமைக்கவும்","email address":"மின்னஞ்சல் முகவரி","confirm password":"கடவுச்சொல்லை உறுதிப்படுத்தவும்","remember me":"என்னை நினைவில் கொள்க","create account":"கணக்கை உருவாக்கவும்","already have an account":"ஏற்கனவே கணக்கு உள்ளதா",
    dashboard:"முகப்புப்பலகை",main:"முதன்மை",details:"விபரங்கள்",organization:"நிறுவனம்",reports:"அறிக்கைகள்",drivers:"சாரதிகள்",logout:"வெளியேறு",welcome:"வரவேற்கிறோம்",overview:"மேலோட்டம்",analytics:"பகுப்பாய்வு",activity:"செயற்பாடு",notifications:"அறிவிப்புகள்",settings:"அமைப்புகள்",profile:"சுயவிவரம்",
    request:"கோரிக்கை",requests:"கோரிக்கைகள்",recommendation:"பரிந்துரை",recommendations:"பரிந்துரைகள்",approval:"அங்கீகாரம்",approvals:"அங்கீகாரங்கள்",journey:"பயணம்",journeys:"பயணங்கள்",trip:"பயணம்",trips:"பயணங்கள்",vehicle:"வாகனம்",vehicles:"வாகனங்கள்",driver:"சாரதி",employee:"ஊழியர்",officer:"அலுவலர்",department:"திணைக்களம்",secretary:"செயலாளர்",user:"பயனர்",
    pending:"நிலுவையில்",approved:"அங்கீகரிக்கப்பட்டது",rejected:"நிராகரிக்கப்பட்டது",returned:"திருப்பப்பட்டது",completed:"முடிந்தது",available:"கிடைக்கிறது",unavailable:"கிடைக்கவில்லை",active:"செயலில்",inactive:"செயலற்றது",maintenance:"பராமரிப்பு",allocated:"ஒதுக்கப்பட்டது",assigned:"நியமிக்கப்பட்டது",submitted:"சமர்ப்பிக்கப்பட்டது",recommended:"பரிந்துரைக்கப்பட்டது",cancelled:"ரத்துசெய்யப்பட்டது",status:"நிலை",priority:"முன்னுரிமை",high:"உயர்",medium:"நடுத்தர",low:"குறைந்த",
    name:"பெயர்",email:"மின்னஞ்சல்",password:"கடவுச்சொல்",phone:"தொலைபேசி",address:"முகவரி",role:"பங்கு",date:"திகதி",time:"நேரம்",from:"இருந்து",to:"வரை",origin:"தொடக்கம்",destination:"இலக்கு",purpose:"நோக்கம்",passengers:"பயணிகள்",notes:"குறிப்புகள்",description:"விளக்கம்",type:"வகை",category:"பிரிவு",registration:"பதிவு",number:"எண்",model:"மாதிரி",make:"தயாரிப்பு",colour:"நிறம்",color:"நிறம்",year:"ஆண்டு",capacity:"கொள்ளளவு",cost:"செலவு",amount:"தொகை",total:"மொத்தம்",fuel:"எரிபொருள்",service:"சேவை",repair:"திருத்தம்",history:"வரலாறு",record:"பதிவு",records:"பதிவுகள்",database:"தரவுத்தளம்",information:"தகவல்",documents:"ஆவணங்கள்",documentation:"ஆவணப்படுத்தல்",
    search:"தேடுக",filter:"வடிகட்டுக",sort:"வரிசைப்படுத்துக",all:"அனைத்தும்",view:"பார்க்க",open:"திறக்க",close:"மூடுக",back:"பின்னால்",next:"அடுத்து",previous:"முந்தைய",edit:"திருத்துக",update:"புதுப்பிக்க",add:"சேர்க்க",remove:"நீக்க",delete:"அழிக்க",save:"சேமிக்க",submit:"சமர்ப்பிக்க",confirm:"உறுதிப்படுத்த",cancel:"ரத்துசெய்ய",approve:"அங்கீகரிக்க",reject:"நிராகரிக்க",return:"திருப்புக",allocate:"ஒதுக்குக",assign:"நியமிக்க",download:"பதிவிறக்க",upload:"பதிவேற்ற",print:"அச்சிட",refresh:"புதுப்பிக்க",clear:"அழிக்க",apply:"பயன்படுத்த",action:"செயல்",actions:"செயல்கள்",
    loading:"ஏற்றுகிறது",saving:"சேமிக்கிறது",submitting:"சமர்ப்பிக்கிறது",processing:"செயலாக்குகிறது",success:"வெற்றி",error:"பிழை",required:"தேவை",optional:"விருப்பம்",yes:"ஆம்",no:"இல்லை",none:"எதுவுமில்லை",other:"வேறு",today:"இன்று",monthly:"மாதாந்த",daily:"தினசரி",current:"தற்போதைய",new:"புதிய",recent:"அண்மைய",select:"தேர்ந்தெடுக்க",enter:"உள்ளிடுக",showing:"காட்டுகிறது",of:"இல்",page:"பக்கம்"
  }
};

export function translatePageText(value, language) {
  if (language === "en" || !value || !/[A-Za-z]/.test(value)) return value;
  const dictionary = pageTranslations[language];
  if (language === "si") {
    const driverCount = value.match(/^\s*(\d+) driver records\s*$/i);
    if (driverCount) return `රියදුරු වාර්තා ${driverCount[1]}ක්`;
    const scheduleCount = value.match(/^\s*Showing (\d+) maintenance schedules\s*$/i);
    if (scheduleCount) return `නඩත්තු කාලසටහන් ${scheduleCount[1]}ක් පෙන්වයි`;
    const vehicleCount = value.match(/^\s*(\d+) matching vehicles\s*$/i);
    if (vehicleCount) return `ගැළපෙන වාහන ${vehicleCount[1]}ක්`;
    const allVehicles = value.match(/^\s*Showing all (\d+) matching vehicles\. Scroll the inventory to view the complete list\s*$/i);
    if (allVehicles) return `ගැළපෙන වාහන ${allVehicles[1]}ම පෙන්වයි. සම්පූර්ණ ලැයිස්තුව බැලීමට ලේඛනය පහළට අනුචලනය (Scroll) කරන්න`;
  }
  const match = value.match(/^(\s*)(.*?)([.!?:…]*)(\s*)$/s);
  if (!match) return value;
  const [, leading, content, punctuation, trailing] = match;
  const translated = dictionary[content.toLowerCase()];
  return translated ? `${leading}${translated}${punctuation}${trailing}` : value;
}
